"""Literature commentaries imported from expert_guided_pinn_annotated.html."""

from __future__ import annotations

from typing import TypedDict, NotRequired


class CommentarySource(TypedDict, total=False):
    text: str
    url: str | None
    verified: bool


class Commentary(TypedDict):
    id: str
    section: str
    category: str
    category_label: str
    marker: str
    title: str
    body: str
    filenote: str
    tagline: str
    anchor_preview: str
    sources: list[CommentarySource]
    proposed_update: NotRequired[str]
    update_details: NotRequired[str]


COMMENTARIES: list[Commentary] = [
    {
        'id': 'n1',
        'section': '1. Introduction',
        'category': 'reliability',
        'category_label': 'LLM Reliability',
        'marker': '¶',
        'title': 'A named risk, now with a taxonomy',
        'body': 'Alansari & Luqman\'s faithfulness taxonomy — instruction, context, and logical inconsistency — explains exactly how "compliance with epidemic logic" hits 90–100% while "compliance with the comment" sits at 6–27% in the same runs. The Fig. 4c case (quadrupling a boundary weight when growth was requested) is instruction inconsistency with locally coherent ODE penalties; the 700-day outbreak blends context and logical inconsistency. The survey\'s own mitigations — Structured CoT for code, semantic-entropy filtering across samples, HalluTree-style claim decomposition — are three concrete builds of the "LLM-loss-semantic-checker" the paper names but doesn\'t implement.',
        'filenote': 'alansari_survey_hallucination.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A published faithfulness taxonomy already explains how epidemic-logic can pass while comment-compliance fails.',
        'proposed_update': 'Apply faithfulness taxonomy for error classification.',
        'update_details': 'Classify LLM failures using Alansari & Luqman\'s categories (instruction, context, logical). Use this taxonomy to refine the Code Tester, targeting "Constant Value Errors" and "Garbage Code" specifically in the verification stage.',
        "sources": [
            {
                "text": 'LLM Hallucination: A Comprehensive Survey — arXiv:2510.06265',
                "url": 'https://arxiv.org/abs/2510.06265',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n2',
        'section': '1. Introduction',
        'category': 'epixai',
        'category_label': 'Epi-XAI Pipeline',
        'marker': '‖',
        'title': 'A training-time patch on top of a five-stage gap',
        'body': "Khalili & Wimmer's PRISMA review of 26 epidemiology+XAI studies proposes a six-stage pipeline — preprocessing, feature engineering, tuning, training, evaluation, explanation — and explicitly flags PINNs as absent from the reviewed literature, naming them for future work this paper is an early instance of. But nearly all of its expert intervention happens at one stage (training, via the loss penalty), leaving data preprocessing, NPI feature engineering, and uncertainty quantification untouched — consistent with the review's broader thesis that pipeline-stage omissions, not any single weak component, are what caps systems like this below deployment readiness.",
        'filenote': 'towardsImprovedXaiBasedEpidemiologicalResearch.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A 26-study epi-XAI review flags PINNs as absent from the literature it surveyed — and names a six-stage pipeline this paper only touches at one stage.',
        'proposed_update': 'Expand expert intervention across the full epi-XAI pipeline.',
        'update_details': 'Extend expert-guided adjustments beyond training-time loss penalties to include data preprocessing and feature engineering. This addresses the six-stage gap identified by Khalili & Wimmer, improving deployment readiness.',
        "sources": [
            {
                "text": 'Khalili & Wimmer (2024), Towards Improved XAI-Based Epidemiological Research into the Next Potential Pandemic',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n3',
        'section': '1. Introduction',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'Lab-in-the-loop: validate the trajectory, not the conjecture',
        'body': 'Möltner et al. build the same expert-comment-to-simulation-code loop for multibody dynamics and tested two validation strategies: the LLM judging its own generated code by conjecture (abandoned — "largely erroneous results, ... disconnect between the generation of the conjecture and the actual simulation model") versus running the actual simulation and having a separate LLM call judge the numerical trajectory ("significantly more reliable"). The PINN Customizer currently does the abandoned version — one LLM invents the loss weights and implicitly judges plausibility, with no trajectory audit before the expert sees the plot — exactly the gap that let the 700-day outbreak compile cleanly.',
        'filenote': 'moeltner_lab_in_the_loop.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A near-identical loop for simulation code found that judging your own generated code by conjecture fails; judging the resulting trajectory works.',
        'proposed_update': 'Implement trajectory-based numerical validation.',
        'update_details': 'Instead of letting the LLM judge its own code "by conjecture," run the simulation and have a separate specialized LLM call (the "Adviser") evaluate the resulting numerical trajectory for epidemiological plausibility.',
        "sources": [
            {
                "text": 'Möltner et al. (2026), Creation, Evaluation and Self-Validation of Simulation Models with LLMs',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n4',
        'section': '2. Methodology',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'Naming the statistics already being done',
        'body': 'Lin\'s contextualist-centrism spectrum gives formal vocabulary for what this decomposition already does without naming it: $L_{data}$ is likelihood/frequentist pressure, the LLM-generated expert penalty is a subjective structural prior, and the epidemic-logic/MAE checks are frequentist filters on a process that is neither pure Bayesian nor pure frequentist. Read this way, edits that are "effectively random rather than logically justified" are Lin\'s bad-prior pathology in a nonparametric weight space — and the planned class-subclass templates are, in Lin\'s terms, a search for an admissible, coherent prior family.',
        'filenote': 'lin_frequentist_or_bayesian.md',
        'tagline': 'Literature comparison',
        'anchor_preview': "This decomposition already is a statistical position — it just isn't named as one.",
        'proposed_update': 'Adopt a formal contextualist-centrism statistical framework.',
        'update_details': 'Reframe PINN loss components ($L_{data}$ vs. $L_{phys}$) as a mix of frequentist likelihoods and subjective structural priors. Use this formal vocabulary to guide the search for an admissible and coherent prior family for expert interventions.',
        "sources": [
            {
                "text": 'Lin (2024), To Be a Frequentist or Bayesian?',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n5',
        'section': '2. Methodology',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'Single-shot is the baseline this architecture was built to beat',
        'body': 'One prompt, one LLM call, a full code artifact in a single pass is exactly the "Single-Shot" configuration Yu et al. test as their weakest baseline for hardware codegen — and it fails all three of their test cases outright. Their working alternative — pseudocode → Python → C++ with a Coder/Verifier pair at each stage, plus a four-branch Reflection agent that can reopen the original instructions rather than just regenerate code — is a tested architecture for the exact gap this paper names but doesn\'t build. Their ablations (removing Understanding, Reflection, or progressive coding one at a time) are also the controlled experiment this paper\'s three-model comparison never runs: it can separate model from architecture; the PINN Customizer can\'t.',
        'filenote': 'yu_2025_spec2rtl_agent.md',
        'tagline': 'Literature comparison',
        'anchor_preview': "This is the exact 'Single-Shot' configuration a hardware-codegen agent tested as its weakest baseline — and it failed every test case.",
        'proposed_update': 'Replace single-shot generation with a multi-stage Coder/Verifier pair.',
        'update_details': 'Move away from one-prompt pass. Implement a progressive architecture: pseudocode → Python → PINN loss, with Reflection agents at each stage to verify against original expert instructions, as proven effective in hardware codegen.',
        "sources": [
            {
                "text": 'Yu et al. (2025), Spec2RTL-Agent: Automated Hardware Code Generation from Complex Specifications',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n6',
        'section': '2.2. Hierarchical text classifier',
        'category': 'explanation',
        'category_label': 'Explanation Theory',
        'marker': '*',
        'title': "The expert already asks contrastive questions — the system doesn't ask back",
        'body': 'Miller\'s survey argues people explain contrastively — fact versus foil, "why P rather than Q" — and socially, not via full causal dumps. The paper\'s successful example ("after the peak there should be a sharper decline") is already exactly this structure, with Table A.2 targeting only the difference, not a full rewrite. The gap Miller predicts and the paper\'s own failures confirm: foils are often implicit, and when the Conversational Agent doesn\'t elicit one explicitly, the LLM guesses wrong — the peak-shift request that produced the 700-day outbreak.',
        'filenote': 'explanationInArtificialIntelligence.md',
        'tagline': 'Literature comparison',
        'anchor_preview': "The paper's successful example is already a textbook contrastive explanation — the system just doesn't ask for the foil explicitly.",
        'proposed_update': 'Elicit explicit foils for contrastive reasoning.',
        'update_details': 'Modify the Conversational Agent to explicitly ask experts for "foils" (why P rather than Q). This enables contrastive explanation as defined by Miller, reducing the likelihood of LLMs guessing the intended forecast shift incorrectly.',
        "sources": [
            {
                "text": 'Explanation in AI: Insights from the Social Sciences — doi:10.1016/j.artint.2018.07.007',
                "url": 'https://doi.org/10.1016/j.artint.2018.07.007',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n7',
        'section': '2.2. Hierarchical text classifier',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'A content ontology without a representation ontology',
        'body': 'Gruber\'s 1993 Ontolingua work solved the identical translation problem three decades early — expressive declarative knowledge (KIF) into restricted executable targets (Loom, Epikit, KEE) — via idiom recognition into a canonical Frame Ontology, then deterministic back-end translators, with no step left to free generation. This paper built the first layer (a four-class comment hierarchy) but skipped the second: "add penalty to term2" is natural-language documentation, not a machine-readable idiom with typed operators and ranges — precisely why two different models can both "honor" the same rule and produce opposite forecasts (weakening vs. quadrupling the same boundary term).',
        'filenote': 'gruber_ontolingua_portable_ontology.md',
        'tagline': 'Literature comparison',
        'anchor_preview': "An ontology architecture from 1993 solved this exact translation problem — with a canonical intermediate form this paper's rules skip.",
        'proposed_update': 'Implement a canonical Frame Ontology for deterministic translation.',
        'update_details': 'Introduce a machine-readable intermediate representation between natural language comments and executable code. Use typed operators and idiom recognition to ensure deterministic translation, eliminating "interpretation" variance between models.',
        "sources": [
            {
                "text": 'Gruber (1993), A Translation Approach to Portable Ontology Specifications',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n8',
        'section': '2.3. PINN Customizer',
        'category': 'reliability',
        'category_label': 'LLM Reliability',
        'marker': '¶',
        'title': 'The compiler catches the minority of errors',
        'body': 'Wang et al.\'s empirical study of HumanEval failures found that 84.21% of incorrect solutions still compile — outside evidence for why a Python-interpreter-only Code Tester lets most semantically wrong loss edits through untouched. Their taxonomy names failures this paper\'s own error list matches almost line for line: Wang et al.\'s «Garbage Code» category (unused variables/constants), «Constant Value Error» (literal numeric insertion, worse in larger models — matching Llama-70B\'s behavior), and errors needing multi-hunk repair, not single-line fixes. Their labeled-repair-prompt experiment raised GPT-4\'s fix rate 4× over unlabeled prompts on the hardest tier — a direct blueprint for a compiler-error-only correction loop.',
        'filenote': 'wang_code_generation_errors.md',
        'tagline': 'Literature comparison',
        'anchor_preview': '84% of incorrect solutions in a benchmark study still compile — the compiler catches only a minority of the errors that matter.',
        'proposed_update': 'Enhance the Code Tester with semantic-entropy filtering.',
        'update_details': 'Supplement simple compilation checks with semantic-entropy analysis to detect "Garbage Code" and "Constant Value Errors." Use labeled-repair prompts for iterative correction when semantic mismatches are detected.',
        "sources": [
            {
                "text": 'Wang et al. (2025), Towards Understanding the Characteristics of Code Generation Errors Made by LLMs',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n9',
        'section': '2.4. Evaluation Approach',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'Confirmation, not verification',
        'body': 'Oreskes et al.\'s classic argument — verification/validation of open natural-system models is logically impossible, only partial confirmation is available, and "a faulty model may appear to be correct" — reframes these four thresholds as confirmation heuristics, a more defensible stance than the abstract\'s language of "confirming feasibility." Multiple loss edits at temperature=1.0 producing visually similar curves with different physics is exactly Oreskes\'s non-uniqueness/underdetermination point, empirically demonstrated in the paper\'s own run-to-run variance.',
        'filenote': 'oreskes_verification_validation.md',
        'tagline': 'Literature comparison',
        'anchor_preview': "Verification is the wrong goal for open natural-system models — and the paper's own multiple-loss-edits-same-plot pattern is exactly the underdetermination this predicts.",
        'proposed_update': 'Shift from "feasibility proof" to "confirmation heuristics."',
        'update_details': 'Position the Expert-Guided PINN as an instrument for "disciplining political dialogue" (Epstein) rather than a truth-machine. Acknowledge and document the non-uniqueness of loss edits that produce similar forecasts.',
        "sources": [
            {
                "text": 'Verification, Validation and Confirmation... — doi:10.1126/science.263.5147.641',
                "url": 'https://doi.org/10.1126/science.263.5147.641',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n10',
        'section': '2.4. Evaluation Approach',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'A patch without an explanation is still soliloquy',
        'body': 'Chakraborti et al.\'s Model Reconciliation framework formalizes exactly what "compliance with the comment" is trying to measure informally: whether a plan — here, the modified forecast — is optimal in the human\'s updated mental model, scored against four named properties: completeness, conciseness, monotonicity, computability. Table A.2\'s "add penalty to term2, other components prohibited" is a Plan Patch Explanation in their terms — it names where to edit, not why that edit reconciles the expert\'s mental model with the PINN\'s, which is exactly why the 700-day outbreak stays inexplicable to the expert even after it compiles.',
        'filenote': 'chakraborti_model_reconciliation.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A formal framework for exactly this kind of patch already exists, with four scoreable properties instead of a visual read.',
        'proposed_update': 'Score modifications against Model Reconciliation properties.',
        'update_details': 'Evaluate all PINN patches against Chakraborti\'s four properties: completeness, conciseness, monotonicity, and computability. This ensures the expert understands *why* an edit reconciles their mental model with the model\'s output.',
        "sources": [
            {
                "text": 'Plan Explanations as Model Reconciliation — arXiv:1701.08317',
                "url": 'https://arxiv.org/abs/1701.08317',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n11',
        'section': '2.4. Evaluation Approach',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'The small model was never given a fair fight',
        'body': 'Kreikemeyer et al. solve the same shape of problem — free text to formal DSL, for chemical reaction networks — and get a 7B model to 84.5% accuracy (vs. 99% for GPT-4o) using three tools Llama-3.1-8B never receives here: LoRA fine-tuning on a synthetic corpus, curated few-shot examples, and optional grammar-constrained decoding. Their own "raw" 8B baseline, given only good few-shot examples, reaches 72.5% — roughly twelve times the 6% reported here for the same size class. That reframes the 8B collapse from "a limit of scale" into an artifact of testing every model size with identical, unaided prompting.',
        'filenote': 'kreikemeyer_2025_llm_reaction_networks.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A 7B model given LoRA fine-tuning, few-shot examples, and grammar-constrained decoding reached 84.5% on a structurally identical task — the small model here got none of those three tools.',
        'proposed_update': 'Fine-tune small models (Llama-8B) for DSL generation.',
        'update_details': 'Apply LoRA fine-tuning on a synthetic dataset of expert-comment-to-DSL pairs. Supplement this with grammar-constrained decoding to ensure that even small models achieve high accuracy in generating valid PINN loss modifications.',
        "sources": [
            {
                "text": 'Kreikemeyer et al. (2025), Using (Not-So) Large Language Models to Generate Simulation Models in a Formal DSL',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n12',
        'section': '2.4. Evaluation Approach',
        'category': 'reliability',
        'category_label': 'LLM Reliability',
        'marker': '¶',
        'title': 'Prototyping at maximum entropy, deployed at low temperature',
        'body': 'Huang et al.\'s survey ties elevated sampling temperature directly to hallucination risk: more uniform token distributions increase tail-token sampling, exactly the mechanism behind the paper\'s own catalog of spurious variables and broken physics at T=1.0. Two of the survey\'s cited mitigations map onto data already produced at no extra cost: self-consistency scoring across the multiple T=1.0 samples per comment (currently discarded after one is shown to the expert), and LMvLM-style cross-examination — an examiner LLM questioning the generator — as a working instantiation of the paper\'s own proposed "LLM-expert-evaluator."',
        'filenote': 'huang_survey_hallucination.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Higher temperature is directly tied to hallucination risk — and the multiple samples this already produces are a free reward-model dataset, currently discarded.',
        'proposed_update': 'Implement self-consistency scoring and cross-examination.',
        'update_details': 'Reduce sampling temperature for deployment. Use self-consistency scoring across multiple T=1.0 samples during development to filter out low-probability hallucinations, and introduce an examiner LLM to critique the generator\'s output.',
        "sources": [
            {
                "text": 'Huang et al. (2024), A Survey on Hallucination in Large Language Models',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n13',
        'section': '3.3. Working with the framework',
        'category': 'alignment',
        'category_label': 'Alignment / RLHF',
        'marker': '⁂',
        'title': "The reward-model dataset already exists — it's being discarded",
        'body': "InstructGPT's core finding is that a model bigger at pretraining but never aligned to instructions loses to a much smaller aligned one — a near match for DeepSeek-V3.1 (671B) topping out at 27% compliance while Ouyang et al.'s 1.3B aligned model beat 175B raw GPT-3. As a proposed extension (not a claim in either paper): two of the three ingredients their reward-model training needs already exist here — multiple candidate loss edits per comment (from T=1.0 sampling) and a three-level expert verdict that is a ready-made ordinal preference signal. The missing step would be saving every candidate and its verdict instead of keeping one and discarding the rest — turning 20-launch prototyping data into training data for a fine-tuned generator the paper does not yet have.",
        'filenote': 'ouyang_2022_instructgpt.md',
        'tagline': 'Literature comparison (proposed extension)',
        'anchor_preview': 'This three-level rating, over multiple sampled candidates, is already two of the three ingredients a reward-model dataset needs.',
        'proposed_update': 'Utilize expert feedback for RLHF-based alignment.',
        'update_details': 'Save all candidate modifications and their associated expert verdicts. Use this data as an ordinal preference signal to train a reward model, aligning the generator more closely with expert intent via Reinforcement Learning from Human Feedback (RLHF).',
        "sources": [
            {
                "text": 'Training LMs to Follow Instructions (InstructGPT) — arXiv:2203.02155',
                "url": 'https://arxiv.org/abs/2203.02155',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n14',
        'section': '4. Limitations and Future work',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'Before writing templates, test which representation wins',
        'body': "Pillay's controlled hyper-heuristic experiment found linear, sequential rule representations beat hierarchical, simultaneously-applied ones on 7 of 8 exam-timetabling benchmarks, and cost far less to search. Table A.2 declares flat, linear rules but hands the LLM free-form Python generation — full hierarchical expressiveness with none of the sequential structure Pillay's result favors. Before building the class-subclass templates already proposed as future work, Pillay's protocol argues for running the same linear-vs-hierarchical ablation on the paper's own 20 comments, rather than picking a representation by default.",
        'filenote': 'burke_heuristic_combination_structure.md — filed under "Burke" in the corpus; the actual source is Pillay (2010)',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A controlled hyper-heuristic experiment found linear rule representations beat hierarchical ones on 7 of 8 benchmarks — this paper declares linear rules but hands the LLM full hierarchical freedom.',
        'proposed_update': 'Test linear vs. hierarchical rule representations.',
        'update_details': 'Conduct ablation studies to determine if linear, sequential rule representations (as favored by Pillay\'s benchmarks) improve reliability over the current hierarchical free-form Python generation for epidemic loss modifications.',
        "sources": [
            {
                "text": 'Pillay (2010), An Empirical Study into the Structure of Heuristic Combinations in an EA Hyper-Heuristic for Examination Timetabling',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n15',
        'section': '4. Limitations and Future work',
        'category': 'explanation',
        'category_label': 'Explanation Theory',
        'marker': '*',
        'title': 'Evaluating for researchers, not for epidemiologists',
        'body': 'Miller\'s "inmates running the asylum" critique — that AI researchers build explanatory systems evaluated by researchers, not intended users — matches the MAE thresholds, n=20, T=1.0, and author-judged compliance here almost point for point. Broekens\' empirically supported finding that different action types need different explanations gives a concrete fix: type the reverse explanation by comment class ("because you cited containment timing") rather than showing only a code diff. Longo\'s physics-versus-biology argument reframes the whole exercise usefully: epidemic policy shifts reshape the effective phase space rather than adding noise inside a fixed SIRD manifold — a stronger, less apologetic reason expert intervention is necessary at all, not a workaround for a model that should otherwise stand alone.',
        'filenote': 'bewareOfInmates_doYouGetIt_howFutureDepends.md — Miller, Broekens & Longo, read together',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A classic XAI critique argues researchers evaluate explanatory systems for themselves, not their intended users — and this evaluation setup matches that pattern closely.',
        'proposed_update': 'Redesign evaluation around epidemiologist user needs.',
        'update_details': 'Move beyond researcher-judged compliance. Implement explanation types based on action categories (e.g., "because you cited containment timing") and use epidemiologist-driven validation to ensure the system meets actual public health decision-making requirements.',
        "sources": [
            {
                "text": 'Miller et al., Beware of Inmates Running the Asylum',
                "url": None,
                "verified": False,
            },
            {
                "text": 'Broekens et al., Do You Get It? User-Evaluated Explainable BDI Agents',
                "url": None,
                "verified": False,
            },
            {
                "text": 'Longo, How the Future Depends on the Past and Rare Events in Systems of Life',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n16',
        'section': '4. Limitations and Future work',
        'category': 'optimization',
        'category_label': 'Active Optimization',
        'marker': '∆',
        'title': 'Paper A as an under-specified deep AO instance',
        'body': 'Wei et al. (2024/25) present DANTE — deep active optimization with neural-surrogate-guided tree exploration. Paper A is a working active-optimization loop that Paper A is a degenerate case of. The transferable thesis is sharp: Paper A\'s expert-in-the-loop cycle is an under-specified deep AO instance whose documented catastrophes are the exact failure modes DANTE names, ablates, and cures.',
        'filenote': 'wei_2024_dante_active_optimization.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Wei et al. (2024/25). DANTE: Deep active optimization for complex systems.',
        'proposed_update': 'Modernize the optimization cycle using neural-surrogate-guided exploration.',
        'update_details': 'Implement a "Surrogate Pre-screen" step: generate k=8/16 variants per step (Best-of-N) and use a lightweight Modification Quality Model (MQM) to select the most promising modification before launching the expensive PINN retraining. This aligns with the DANTE methodology.',
        "sources": [
            {
                "text": 'Wei et al. (2024/25). DANTE: Deep active optimization for complex systems.',
                "url": 'https://doi.org/10.1038/s43588-025-00858-x',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n17',
        'section': '4. Limitations and Future work',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': 'Σ',
        'title': 'Decoupling reasoning quality from answer correctness',
        'body': 'Zhang et al. (2026) introduce the TRM-Preference dataset and train a Bradley–Terry Thinking Reward Model (TRM). TRM is trained exclusively on verified-correct reasoning pairs, decoupling reasoning quality from answer correctness — the same decoupling Paper A performs verbally but never operationalizes.',
        'filenote': 'zhang_2026_trm_complex_reasoning.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Bradley-Terry Thinking Reward Model, которая разделяет «следование инструкции» и «точность прогноза».',
        'proposed_update': 'Introduce a Bradley–Terry Thinking Reward Model (TRM) for objective assessment.',
        'update_details': 'Transition from subjective "Compliance with the comment" to a TRM-based quality score. Collect comparison pairs from expert epidemiologists and train a small model (e.g., Llama-8B) to distinguish between effective and ineffective reasoning paths.',
        "sources": [
            {
                "text": 'Zhang et al. (2026). Characterizing, Evaluating, and Optimizing Complex Reasoning.',
                "url": 'https://arxiv.org/abs/2602.08498',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n18',
        'section': '4. Limitations and Future work',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': 'Σ',
        'title': 'Future-work "LLM-expert-evaluator" is Paper B\'s TRM',
        'body': 'Paper A explicitly names an LLM-based evaluator as the mechanism that would close its own subjectivity gap. Paper B trains one, publishes the dataset, and shows it works both as a selector and as a training signal.',
        'filenote': 'zhang_2026_trm_complex_reasoning.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Согласно Zhang et al. (2026, TRM), эта проблема решается через Bradley-Terry Thinking Reward Model',
        'proposed_update': 'Build an automated "Modification Quality Model" (MQM) judge.',
        'update_details': 'Develop an LLM-based judge (e.g., Llama-8B) trained on TRM datasets to evaluate PINN modifications. The MQM should separate macro-effectiveness (validity of the epidemic curve) from micro-effectiveness (code cleanliness), providing a consistent signal for the optimization loop.',
        "sources": [
            {
                "text": 'Zhang et al. (2026). Characterizing, Evaluating, and Optimizing Complex Reasoning.',
                "url": 'https://arxiv.org/abs/2602.08498',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n19',
        'section': '2.4. Evaluation Approach',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': 'Ω',
        'title': 'Statistical inseparability and non-parametric tests',
        'body': 'Eftimov & Korošec (2019) show that for distributions like those in Paper A, non-parametric tests (Anderson-Darling) and Bonferroni corrections are necessary, otherwise conclusions about model superiority are unfounded.',
        'filenote': 'eftimov_2019_edsc_statistical_comparison.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Согласно Eftimov & Korošec (2019, eDSC), для таких распределений необходимы непараметрические тесты',
        'proposed_update': 'Apply non-parametric statistical tests and Bonferroni corrections.',
        'update_details': 'Use Anderson-Darling tests to handle non-Gaussian performance distributions across model runs. Implement Bonferroni corrections to ensure that observed differences between models (e.g., Llama vs DeepSeek) are statistically significant and not mere noise.',
        "sources": [
            {
                "text": 'Eftimov & Korošec (2019). eDSC: A new approach to statistical comparison of meta-heuristic algorithms.',
                "url": 'https://doi.org/10.1016/j.ins.2019.03.049',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n20',
        'section': '3.4. Framework performance',
        'category': 'pathology',
        'category_label': 'Loss Landscapes',
        'marker': '⊗',
        'title': 'Pathologies of coupled loss landscapes',
        'body': 'Malan (2021) and Daza (2016) show that modification of PINN loss weights creates fractal basin boundaries where the model "falls through." This is a fundamental instability, not just an LLM code error.',
        'filenote': 'malan_2021_landscape_analysis_survey.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'теория Malan (2021) и Daza (2016) показывает, что это классические «патологии сопряженных ландшафтов».',
        'proposed_update': 'Diagnose and mitigate loss landscape pathologies using basin entropy analysis.',
        'update_details': 'Investigate the fractal boundaries of attractor basins created by composite loss modifications. Use Daza\'s basin entropy metric to identify regions where PINN stability "falls through," treating "catastrophic outcomes" as fundamental landscape features rather than simple code errors.',
        "sources": [
            {
                "text": 'Malan (2021). Landscape Analysis for Optimization: A Survey.',
                "url": 'https://doi.org/10.3390/a14020040',
                "verified": True,
            },
            {
                "text": 'Daza et al. (2016). Basin entropy: a new tool to analyze uncertainty in dynamical systems.',
                "url": 'https://doi.org/10.1038/srep31416',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n21',
        'section': '2.2. Hierarchical text classifier',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'An expert system without competency questions',
        'body': 'Noy & McGuinness (2001) state that the absence of a formal ontology and competency questions makes the rule base fragile and difficult to extend.',
        'filenote': 'noy_2001_ontology_development_101.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'отсутствие формальной онтологии (competency questions) делает базу правил (Appendix A) хрупкой и труднорасширяемой.',
        'proposed_update': 'Formalize the expert rule base using a structured ontology (DSL).',
        'update_details': 'Define "competency questions" to delineate the expert knowledge domain. Replace the ad hoc textual rules in Appendix A with a formal hierarchy of classes and typed JSON-schemas/DSL templates to prevent structural errors like literal number insertion.',
        "sources": [
            {
                "text": 'Noy & McGuinness (2001). Ontology Development 101.',
                "url": 'https://protege.stanford.edu/publications/ontology_development/ontology101.pdf',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n22',
        'section': '2. Methodology',
        'category': 'optimization',
        'category_label': 'Active Optimization',
        'marker': '∆',
        'title': 'Reward-as-code and the Eureka basis',
        'body': 'Ma et al. (2023) Eureka demonstrates generating reward functions as code. This is the underlying basis of the method used in Paper A for PINN loss modification.',
        'filenote': 'article/analysis/ouyang_2022_instructgpt.md', # Placeholder, Eureka usually cited with reward-as-code
        'tagline': 'Literature comparison',
        'anchor_preview': 'Ma et al. (2023). Eureka. Генерация reward-функций как кода (базис метода).',
        'proposed_update': 'Adopt the Eureka reward-as-code paradigm for loss generation.',
        'update_details': 'Refactor the PINN loss modification module to treat reward/loss functions as executable code snippets. Use the Eureka approach to allow LLMs to iteratively refine these functions based on environment feedback, rather than just adjusting numeric weights.',
        "sources": [
            {
                "text": 'Ma et al. (2023). Eureka: Human-Level Reward Design via Coding Large Language Models.',
                "url": 'https://arxiv.org/abs/2310.12931',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n23',
        'section': '4. Limitations and Future work',
        'category': 'explanation',
        'category_label': 'Explanation Theory',
        'marker': '*',
        'title': 'Contrastive Explanation: Why here and not there?',
        'body': 'Miller (2020) argues for evaluating success through contrast: "why did the forecast move exactly there, and not elsewhere?" This is a key missing metric in Paper A.',
        'filenote': 'miller_2020_contrastive_explanation.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Miller (2020). Contrastive Explanation. Оценка успеха через контраст',
        'proposed_update': 'Implement contrastive evaluation of forecast adjustments.',
        'update_details': 'Instead of absolute accuracy, evaluate "why the forecast moved in a specific direction." Use contrastive explanation metrics to verify if the LLM-induced shift aligns with the expert\'s stated intent (e.g., "why higher peak and not later peak?").',
        "sources": [
            {
                "text": 'Miller (2020). Contrastive Explanation: A Survey.',
                "url": 'https://arxiv.org/abs/1811.03163',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n24',
        'section': '4. Limitations and Future work',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'Grammatical Evolution and DSL constraints',
        'body': 'Hidalgo et al. (2018) use DSLs and grammars to constrain LLMs, warning that too rigid rules can reduce accuracy but prevent "literal number insertion" errors.',
        'filenote': 'hidalgo_2018_glucose_grammatical_evolution.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Hidalgo et al. (2018). Glucose Prognosis by Grammatical Evolution. Использование грамматик (DSL) для ограничения LLM.',
        'proposed_update': 'Integrate Grammatical Evolution for constrained LLM output.',
        'update_details': 'Use context-free grammars or DSLs to restrict the LLM\'s generation space. This ensures that modifications to PINN physics-informed losses follow strict epidemiological syntax, preventing hallucinations and invalid mathematical expressions.',
        "sources": [
            {
                "text": 'Hidalgo et al. (2018). Glucose Prognosis by Grammatical Evolution.',
                "url": 'https://doi.org/10.1007/978-3-319-74718-7_55',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n25',
        'section': '4. Limitations and Future work',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'Ontology Development 101',
        'body': 'Noy & McGuinness (2001) provide a methodology for building class hierarchies, which could replace the ad hoc Table A.2.',
        'filenote': 'noy_2001_ontology_development_101.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Noy & McGuinness (2001). Ontology Development 101. Методология построения иерархии классов',
        'proposed_update': 'Develop a formal epidemiological ontology for the classifier.',
        'update_details': 'Replace ad-hoc BERT classification with a formal ontology based on Noy & McGuinness methodology. This involves defining classes, properties, and constraints that represent epidemic dynamics, making the "Expert" part of the system more robust and explainable.',
        "sources": [
            {
                "text": 'Noy & McGuinness (2001). Ontology Development 101.',
                "url": 'https://protege.stanford.edu/publications/ontology_development/ontology101.pdf',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n26',
        'section': '4. Limitations and Future work',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'Multi-Agent Collaboration in optimization',
        'body': 'Malek (2009) describes architectures where a generator, an adviser, and a pool of solutions interact — a blueprint for the proposed multi-agent Future Work.',
        'filenote': 'malek_2009_multi_agent_collaboration.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Malek (2009). Meta-Heuristic Collaboration in a MAS. Архитектура для Future Work',
        'proposed_update': 'Transition to a Multi-Agent System (MAS) architecture.',
        'update_details': 'Redesign the framework to use multiple specialized agents: a generator for loss functions, an "Adviser" for critique, and a supervisor for solution pool management. This enables meta-heuristic collaboration as described by Malek (2009).',
        "sources": [
            {
                "text": 'Malek (2009). Meta-Heuristic Collaboration in a MAS.',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n27',
        'section': '4. Limitations and Future work',
        'category': 'explanation',
        'category_label': 'Explanation Theory',
        'marker': '*',
        'title': 'Actual Cause and Causal Explanations',
        'body': 'Halpern & Pearl (2005) provide a formal basis for checking if an LLM edit is the "actual cause" of a forecast change, rather than a coincidental side effect.',
        'filenote': 'halpern_pearl_2005_causes_and_explanations.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Halpern & Pearl (2005). Causes and Explanations. Формальная база для проверки того, является ли правка LLM',
        'proposed_update': 'Verify causal impact of LLM modifications.',
        'update_details': 'Use Halpern & Pearl\'s "Actual Cause" framework to strictly prove that a specific LLM code modification is the actual cause of a forecast change. This prevents misattributing stochastic PINN convergence improvements to LLM reasoning.',
        "sources": [
            {
                "text": 'Halpern & Pearl (2005). Causes and Explanations.',
                "url": 'https://arxiv.org/abs/cs/0011012',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n28',
        'section': '4. Limitations and Future work',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'Knowledge Engineering and DSLs',
        'body': 'Studer et al. (1998) and Gruber (1993) highlight that without semantic transparency, modifications are effectively random. This paper\'s Appendix A is insufficient for meaningful control.',
        'filenote': 'studer_1998_knowledge_engineering.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'The current study is limited by the lack of mechanisms to control the interpretability of the generated loss functions.',
        'proposed_update': 'Improve semantic transparency of generated losses.',
        'update_details': 'Apply Knowledge Engineering principles from Studer/Gruber to ensure generated loss components have clear physical/epidemiological meaning. Move away from "black-box" modifications toward interpretable, symbolic loss terms.',
        "sources": [
            {
                "text": 'Studer et al. (1998). Knowledge Engineering: Principles and Methods.',
                "url": 'https://doi.org/10.1016/S0169-023X(97)00056-6',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n29',
        'section': '3.4. Framework performance',
        'category': 'pathology',
        'category_label': 'Loss Landscapes',
        'marker': '⊗',
        'title': 'Past-dependence and rare events',
        'body': 'Longo argues that biological and social systems (like epidemics) reshape their own phase space through rare events, making static PINN models fundamentally limited without expert steering.',
        'filenote': 'bewareOfInmates_doYouGetIt_howFutureDepends.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Longo, How the Future Depends on the Past and Rare Events in Systems of Life',
        'proposed_update': 'Integrate non-static epidemic priors.',
        'update_details': 'Account for "rare events" and structural shifts in epidemic phase space as described by Longo. Move beyond fixed SIRD manifolds to models that can adapt their own parameters when expert intervention signals a fundamental regime change.',
        "sources": [
            {
                "text": 'Longo, How the Future Depends on the Past and Rare Events in Systems of Life',
                "url": 'https://doi.org/10.1007/s10699-017-9535-x',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n30',
        'section': '3.3. Working with the framework',
        'category': 'explanation',
        'category_label': 'Explanation Theory',
        'marker': '*',
        'title': 'User-evaluated explainable agents',
        'body': 'Broekens et al. show that different action types require different explanation styles. Showing code diffs to epidemiologists (the "inmate" problem) is suboptimal.',
        'filenote': 'bewareOfInmates_doYouGetIt_howFutureDepends.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Broekens et al., Do You Get It? User-Evaluated Explainable BDI Agents',
        'proposed_update': 'Tailor explanation styles to expert user roles.',
        'update_details': 'Implement diverse explanation modalities (visual, textual, causal) tailored to epidemiologists rather than AI researchers. Verify "understanding" via task-specific evaluation as proposed by Broekens.',
        "sources": [
            {
                "text": 'Broekens et al., Do You Get It? User-Evaluated Explainable BDI Agents',
                "url": 'https://doi.org/10.1007/978-3-642-16178-0_5',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n31',
        'section': '4. Limitations and Future work',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'Beware of inmates running the asylum',
        'body': 'Miller\'s critique applies here: researchers evaluating their own system with researchers\' metrics (MAE) instead of domain-relevant outcomes for epidemiologists.',
        'filenote': 'bewareOfInmates_doYouGetIt_howFutureDepends.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Miller et al., Beware of Inmates Running the Asylum',
        'proposed_update': 'Shift evaluation focus to domain-relevant outcomes.',
        'update_details': 'Replace researcher-centric metrics (MAE, Loss) with epidemiological outcomes (peak timing accuracy, NPI impact estimation). Ensure evaluation involves domain experts in a structured, non-subjective way.',
        "sources": [
            {
                "text": 'Miller et al., Beware of Inmates Running the Asylum',
                "url": 'https://arxiv.org/abs/1712.00547',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n32',
        'section': '4. Limitations and Future work',
        'category': 'optimization',
        'category_label': 'Active Optimization',
        'marker': '∆',
        'title': 'Heuristic combination structure',
        'body': 'Pillay (2010) study on hyper-heuristics shows that the structure of how heuristics are combined (like loss terms in PINN) determines the search efficiency.',
        'filenote': 'burke_heuristic_combination_structure.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Pillay (2010), An Empirical Study into the Structure of Heuristic Combinations',
        'proposed_update': 'Optimize the structure of composite loss combinations.',
        'update_details': 'Apply hyper-heuristic optimization to the way expert penalties are combined with physics-informed losses. Test if linear or hierarchical combinations provide better stability for epidemic forecasts.',
        "sources": [
            {
                "text": 'Pillay (2010), An Empirical Study into the Structure of Heuristic Combinations',
                "url": 'https://doi.org/10.1145/1899503.1899531',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n33',
        'section': '2. Methodology',
        'category': 'reliability',
        'category_label': 'LLM Reliability',
        'marker': '¶',
        'title': 'Hallucination in Large Language Models',
        'body': 'Huang et al. (2024) survey provides a framework for understanding and mitigating hallucinations, which are a critical risk in generating PINN loss code.',
        'filenote': 'huang_survey_hallucination.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Huang et al. (2024), A Survey on Hallucination in Large Language Models',
        'proposed_update': 'Mitigate hallucinations in PINN loss generation.',
        'update_details': 'Apply hallucination detection techniques (e.g., self-consistency checks) to every generated loss code snippet. Use domain-specific "fact-checkers" to ensure generated ODE terms are mathematically valid.',
        "sources": [
            {
                "text": 'Huang et al. (2024), A Survey on Hallucination in Large Language Models',
                "url": 'https://doi.org/10.1145/3703155',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n34',
        'section': '2. Methodology',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'Generating simulation models in DSL',
        'body': 'Kreikemeyer et al. (2025) show that using DSLs for model generation significantly improves reliability and reduces hallucinations compared to raw code.',
        'filenote': 'kreikemeyer_2025_llm_reaction_networks.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Kreikemeyer et al. (2025), Using (Not-So) Large Language Models to Generate Simulation Models',
        'proposed_update': 'Use specialized LLMs for reaction-network modeling.',
        'update_details': 'Leverage fine-tuned models optimized for reaction-network DSLs to generate PINN physics losses. This reduces generation errors compared to using generic instruction-tuned models.',
        "sources": [
            {
                "text": 'Kreikemeyer et al. (2025), Using (Not-So) Large Language Models to Generate Simulation Models in a Formal DSL',
                "url": 'https://arxiv.org/abs/2503.01675',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n35',
        'section': '3.2. Code correctness',
        'category': 'reliability',
        'category_label': 'LLM Reliability',
        'marker': '¶',
        'title': 'Characteristics of code generation errors',
        'body': 'Wang et al. (2025) analyze common error patterns in LLM-generated code, many of which (unused variables, constant errors) are seen in Paper A.',
        'filenote': 'wang_code_generation_errors.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Wang et al. (2025), Towards Understanding the Characteristics of Code Generation Errors',
        'proposed_update': 'Target specific code generation failure modes.',
        'update_details': 'Identify and fix common LLM code errors like "literal number insertion" and "unused variables" in the PINN Customizer. Implement automated repair hunks for these specific failure categories.',
        "sources": [
            {
                "text": 'Wang et al. (2025), Towards Understanding the Characteristics of Code Generation Errors Made by LLMs',
                "url": 'https://arxiv.org/abs/2406.08731',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n36',
        'section': '2.2. Hierarchical text classifier',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'Portable Ontology Specifications',
        'body': 'Gruber (1993) defines the foundations for portable ontologies, essential for creating shareable and extensible expert knowledge bases.',
        'filenote': 'gruber_ontolingua_portable_ontology.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Gruber (1993), A Translation Approach to Portable Ontology Specifications',
        'proposed_update': 'Establish a portable ontology for epidemic dynamics.',
        'update_details': 'Use Gruber\'s translation approach to create a shared ontology for epidemic modeling. This allows expert knowledge to be ported between different modeling frameworks (PINNs, SIRD, agents).',
        "sources": [
            {
                "text": 'Gruber (1993), A Translation Approach to Portable Ontology Specifications',
                "url": 'https://doi.org/10.1006/knac.1993.1008',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n37',
        'section': '2. Methodology',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'Automated Hardware Code Generation',
        'body': 'Yu et al. (2025) present a multi-agent approach (Spec2RTL) that could be adapted for generating complex PINN loss functions from specifications.',
        'filenote': 'yu_2025_spec2rtl_agent.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Yu et al. (2025), Spec2RTL-Agent: Automated Hardware Code Generation',
        'proposed_update': 'Implement multi-stage reflection for loss generation.',
        'update_details': 'Use Understanding and Reflection stages to verify every generated loss term against the original expert comment before training, mimicking the Spec2RTL-Agent architecture.',
        "sources": [
            {
                "text": 'Yu et al. (2025), Spec2RTL-Agent: Automated Hardware Code Generation from Complex Specifications',
                "url": 'https://arxiv.org/abs/2506.13905',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n38',
        'section': '2. Methodology',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'Frequentist or Bayesian?',
        'body': 'Lin (2024) discusses the philosophical divide in modeling, relevant to how expert "priors" are integrated into PINN "data" via loss terms.',
        'filenote': 'lin_frequentist_or_bayesian.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Lin (2024), To Be a Frequentist or Bayesian?',
        'proposed_update': 'Formalize the Bayesian-frequentist hybrid in PINNs.',
        'update_details': 'Apply Lin\'s framework to treat physics losses as structural priors and data losses as likelihoods, providing a rigorous statistical foundation for expert-guided modeling.',
        "sources": [
            {
                "text": 'Lin (2024), To Be a Frequentist or Bayesian?',
                "url": 'https://doi.org/10.1162/99608f92.9a53b923',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n39',
        'section': '4. Limitations and Future work',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'Self-Validation of Simulation Models',
        'body': 'Möltner et al. (2026) explore how LLMs can validate the models they generate, a direct parallel to the proposed "LLM-expert-evaluator."',
        'filenote': 'moeltner_lab_in_the_loop.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Möltner et al. (2026), Creation, Evaluation and Self-Validation of Simulation Models with LLMs',
        'proposed_update': 'Implement trajectory-based numerical validation.',
        'update_details': 'Instead of letting the LLM judge its own code "by conjecture," run the simulation and have a separate specialized LLM call (the "Adviser") evaluate the resulting numerical trajectory for epidemiological plausibility.',
        "sources": [
            {
                "text": 'Möltner et al. (2026), Creation, Evaluation and Self-Validation of Simulation Models with LLMs',
                "url": 'https://doi.org/10.1016/j.neucom.2025.132030',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n40',
        'section': '1. Introduction',
        'category': 'alignment',
        'category_label': 'Alignment / RLHF',
        'marker': '⁂',
        'title': 'Improved XAI for Epidemiology',
        'body': 'Khalili & Wimmer (2024) emphasize the need for human-centered XAI in pandemic research, providing context for why expert-guided PINNs are needed.',
        'filenote': 'towardsImprovedXaiBasedEpidemiologicalResearch.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Khalili & Wimmer (2024), Towards Improved XAI-Based Epidemiological Research',
        'proposed_update': 'Expand expert intervention across the full epi-XAI pipeline.',
        'update_details': 'Extend expert-guided adjustments beyond training-time loss penalties to include data preprocessing and feature engineering. This addresses the six-stage gap identified by Khalili & Wimmer, improving deployment readiness.',
        "sources": [
            {
                "text": 'Khalili & Wimmer (2024), Towards Improved XAI-Based Epidemiological Research into the Next Potential Pandemic',
                "url": 'https://doi.org/10.3390/life14070783',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n41',
        'section': '3.3. Working with the framework',
        'category': 'explanation',
        'category_label': 'Explanation Theory',
        'marker': '*',
        'title': 'Dialogue and Explanation',
        'body': 'Walton (2010) and Arioua (2015) formalize explanatory dialogues, which could structure the interaction between the conversational agent and the expert.',
        'filenote': 'walton_2010_dialogue_explanation.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'The interaction with the framework proceeds through the following steps:',
        'proposed_update': 'Adopt a formal dialogue theory for expert interaction.',
        'update_details': 'Structure the conversational agent\'s interactions using Walton\'s dialogue theory and Arioua\'s MAS explanatory dialogue frameworks. This ensures a systematic elicitation of expert knowledge and clearer explanations of model changes.',
        "sources": [
            {
                "text": 'Walton (2010). Dialogue Theory for Critical Argumentation.',
                "url": 'https://doi.org/10.1007/s11229-010-9745-z',
                "verified": True,
            },
            {
                "text": 'Arioua et al. (2015). Explanatory Dialogues in Multi-Agent Systems.',
                "url": 'https://doi.org/10.1007/978-3-319-23540-0_19',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n42',
        'section': '2.4. Evaluation Approach',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'Inconsistency in Probabilistic Knowledge Bases',
        'body': 'Dubois (2015) and Potyka (2015) discuss managing inconsistent expert knowledge in probabilistic systems, relevant to noisy epidemiological data.',
        'filenote': 'dubois_2015_possibilistic_inconsistency.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'The analysis was conducted on daily and cumulative incidence data',
        'proposed_update': 'Manage inconsistent expert knowledge via priority-based KBs.',
        'update_details': 'Implement possibilistic treatment (Dubois) and priority-based probabilistic knowledge bases (Potyka) to handle contradictory expert comments and noisy epidemic data, ensuring more stable model updates.',
        "sources": [
            {
                "text": 'Dubois et al. (2015). Possibilistic Treatment of Inconsistency.',
                "url": 'https://doi.org/10.1007/978-3-319-23540-0_23',
                "verified": True,
            },
            {
                "text": 'Potyka (2015). Priority and Probabilistic Knowledge Bases.',
                "url": 'https://doi.org/10.1007/978-3-319-23540-0_9',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n43',
        'section': '3.4. Framework performance',
        'category': 'pathology',
        'category_label': 'Loss Landscapes',
        'marker': '⊗',
        'title': 'Basin Entropy and Dynamical Uncertainty',
        'body': 'Daza (2016) introduces basin entropy to measure uncertainty in systems with multiple attractors, explaining why some PINN modifications "stall."',
        'filenote': 'daza_2016_basin_entropy.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'We hypothesize that discrepancies between the forecast and training data (Figure 5)',
        'proposed_update': 'Diagnose dynamical uncertainty using basin entropy.',
        'update_details': 'Apply Daza\'s basin entropy metric to quantify the uncertainty and stability of PINN forecasts after expert intervention. Identify "stall" regions in the loss landscape where the model fails to adapt to new expert constraints.',
        "sources": [
            {
                "text": 'Daza et al. (2016). Basin entropy: a new tool to analyze uncertainty in dynamical systems.',
                "url": 'https://doi.org/10.1038/srep31416',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n44',
        'section': '4. Limitations and Future work',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'Multi-Agent Collaboration',
        'body': 'Malek (2009) provides the theoretical framework for meta-heuristic collaboration in multi-agent systems, as proposed in the Future Work section.',
        'filenote': 'malek_2009_multi_agent_collaboration.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'A promising direction is to evolve the system toward a multi-agent architecture',
        'proposed_update': 'Redesign as a Multi-Agent System (MAS).',
        'update_details': 'Implement Malek\'s (2009) architecture for meta-heuristic collaboration. Use specialized agents (Generator, Adviser, Supervisor) to manage the solution pool, enabling complex multi-stage expert interventions that a single agent cannot handle.',
        "sources": [
            {
                "text": 'Malek (2009). Meta-Heuristic Collaboration in a MAS.',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n45',
        'section': '5. Conclusion',
        'category': 'alignment',
        'category_label': 'Alignment / RLHF',
        'marker': '⁂',
        'title': 'Operational Forecasting Calibration',
        'body': 'Hadjimichael (1993) discusses interactive inductive learning for expert systems, an early precursor to expert-guided PINN calibration.',
        'filenote': 'hadjimichael_1993_interactive_inductive.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Experience with operational forecasting indicates the need for periodic calibration',
        'proposed_update': 'Implement interactive inductive learning for calibration.',
        'update_details': 'Use Hadjimichael\'s (1993) interactive inductive learning to periodically recalibrate the expert-guided loop. This allows the system to learn from its own forecasting errors and refine its expert-aligned priors over time.',
        "sources": [
            {
                "text": 'Hadjimichael (1993). Interactive Inductive Learning.',
                "url": 'https://doi.org/10.1006/imms.1993.1008',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n46',
        'section': '5. Conclusion',
        'category': 'alignment',
        'category_label': 'Alignment / RLHF',
        'marker': '⁂',
        'title': 'Operator Competence and AI interaction',
        'body': 'Epstein (2008) argues that models are tools for "disciplining dialogue," making operator competence more important than pure model accuracy.',
        'filenote': 'epstein_2008_why_model.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'The impact of operator competence and their understanding of how large language models function',
        'proposed_update': 'Reframe modeling as "disciplining political dialogue."',
        'update_details': 'Adopt Epstein\'s (2008) "Why Model?" thesis. Position the framework as a tool for experts to explore uncertainties and illustrate the consequences of different assumptions, rather than purely as a predictive "black box."',
        "sources": [
            {
                "text": 'Epstein (2008). Why Model?',
                "url": 'https://jasss.soc.surrey.ac.uk/11/4/12.html',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n47',
        'section': '5. Conclusion',
        'category': 'architecture',
        'category_label': 'Agent Architecture',
        'marker': '‡',
        'title': 'Initial step towards Expert-Guided systems',
        'body': 'Steiner (2024) and Tonda (2013) provide examples of steering complex networks and Bayesian interaction that validate the "initial step" framing.',
        'filenote': 'steiner_2024_steering_wheel_crn.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'This study presents an initial step in this direction in the form of the experimental Expert-Guided PINN framework',
        'proposed_update': 'Implement active steering of chemical/epidemic networks.',
        'update_details': 'Apply Steiner\'s (2024) steering methodology to epidemic dynamics. Use expert-guided loss terms to "drive" the epidemic model toward specific desired behaviors, treating the forecasting process as an active control task.',
        "sources": [
            {
                "text": 'Steiner et al. (2024). Steering complex chemical reaction networks.',
                "url": 'https://doi.org/10.1038/s41467-024-47997-9',
                "verified": True,
            },
            {
                "text": 'Tonda et al. (2013). Bayesian Network Structure Learning with Interaction.',
                "url": 'https://doi.org/10.1007/978-3-319-11683-9_17',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n48',
        'section': '2. Methodology',
        'category': 'formalization',
        'category_label': 'Formalization & Ontology',
        'marker': '†',
        'title': 'Bipolar Change and Argumentation',
        'body': 'Cayrol (2015) and Amgoud (2015) discuss bipolar argumentation and undercutting, relevant to how expert comments conflict with or "undercut" PINN ODE residuals.',
        'filenote': 'cayrol_2015_bipolar_change.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'The define characteristic of the PINN methodology is the optimization of a composite loss function',
        'proposed_update': 'Model expert-physics conflict as bipolar argumentation.',
        'update_details': 'Use bipolar argumentation frameworks (Cayrol/Amgoud) to formalize the interaction between data-driven residuals and expert-driven penalties. This allows for principled resolution when expert comments "undercut" the underlying ODE physics.',
        "sources": [
            {
                "text": 'Cayrol et al. (2015). Bipolar Change in Argumentation.',
                "url": 'https://doi.org/10.1007/978-3-319-23540-0_21',
                "verified": True,
            },
            {
                "text": 'Amgoud et al. (2015). Undercutting in Argumentation.',
                "url": 'https://doi.org/10.1007/978-3-319-23540-0_18',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n49',
        'section': '3.4. Framework performance',
        'category': 'pathology',
        'category_label': 'Loss Landscapes',
        'marker': '⊗',
        'title': 'Funnel entrapment and stalled forecasts',
        'body': 'Ochoa & Veerapen (2016) challenge the "big valley" hypothesis, showing that search landscapes decompose into disconnected funnels. If PINN weights are trapped in a sub-optimal funnel, even a modified loss may fail to move the forecast — explaining the 15-28% "unchanged" subset.',
        'filenote': 'clark_deconstructing_big_valley.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Paper B (Ochoa and Veerapen, 2016) uses local optima networks (LON) to show that the classic “big valley” decomposes into disconnected funnels.',
        "sources": [
            {
                "text": 'Ochoa & Veerapen (2016). Deconstructing the Big Valley Search Space Hypothesis.',
                "url": 'https://doi.org/10.1145/2908812.2908848',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n50',
        'section': '2. Methodology',
        'category': 'pathology',
        'category_label': 'Loss Landscapes',
        'marker': '⊗',
        'title': 'Gradient walks and NN landscapes',
        'body': 'Malan et al. study the effect of gradient walks on neural network landscapes, highlighting how landscape features (like ridges or basins) influence the success of optimization under modified objectives.',
        'filenote': 'malan_gradient_walk_nn_landscapes.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Malan et al. study how landscape features influence the success of optimization.',
        "sources": [
            {
                "text": 'Malan et al. (2021). Landscape Analysis for Optimization: A Survey.',
                "url": 'https://doi.org/10.3390/a14020040',
                "verified": True,
            },
        ],
    },
    {
        'id': 'n51',
        'section': '2. Methodology',
        'category': 'pathology',
        'category_label': 'Loss Landscapes',
        'marker': '⊗',
        'title': 'Landscape features under noise',
        'body': 'Abell et al. analyze how landscape features behave under noise, relevant to the "stochastic" nature of LLM-generated loss modifications and their impact on PINN training stability.',
        'filenote': 'abell_landscape_features_under_noise.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Abell et al. analyze how landscape features behave under noise.',
        "sources": [
            {
                "text": 'Abell et al. (2024). Landscape features under noise.',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n52',
        'section': '4. Limitations and Future work',
        'category': 'optimization',
        'category_label': 'Active Optimization',
        'marker': '∆',
        'title': 'Algorithm Selection Challenge',
        'body': "O'Mahony et al. discuss the ICON algorithm selection challenge, providing a framework for choosing the best optimizer/model for a given task, which could be integrated into the PINN Customizer.",
        'filenote': 'omahony_icon_algorithm_selection_challenge.md',
        'tagline': 'Literature comparison',
        'anchor_preview': "O'Mahony et al. discuss the ICON algorithm selection challenge.",
        "sources": [
            {
                "text": "O'Mahony et al. (2024). ICON Algorithm Selection Challenge.",
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n53',
        'section': '5. Conclusion',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'Unpredictability and Irreducibility',
        'body': 'Wolfram (2023) discusses computational irreducibility, arguing that some system behaviors cannot be predicted without simulation, justifying the "expert-in-the-loop" need for complex epidemics.',
        'filenote': 'unpredictabilityAndComputationalIrreducibility.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Some system behaviors cannot be predicted without simulation.',
        "sources": [
            {
                "text": 'Wolfram (2023). Unpredictability and Computational Irreducibility.',
                "url": None,
                "verified": False,
            },
        ],
    },
    {
        'id': 'n54',
        'section': '5. Conclusion',
        'category': 'evaluation',
        'category_label': 'Evaluation Epistemics',
        'marker': '§',
        'title': 'Weak Emergence and Modeling',
        'body': 'Bedau (1997) defines weak emergence as behavior that is only reachable through simulation. This reframes Paper A as a tool for exploring emergent epidemiological patterns.',
        'filenote': 'weakEmergence.md',
        'tagline': 'Literature comparison',
        'anchor_preview': 'Weak emergence as behavior that is only reachable through simulation.',
        "sources": [
            {
                "text": 'Bedau (1997). Weak Emergence.',
                "url": None,
                "verified": False,
            },
        ],
    },
]


def commentaries_by_section() -> dict[str, list[Commentary]]:
    grouped: dict[str, list[Commentary]] = {}
    for commentary in COMMENTARIES:
        grouped.setdefault(commentary["section"], []).append(commentary)
    return grouped


ANNOTATED_SECTIONS: list[str] = list(commentaries_by_section().keys())
