"""Input and output helpers for rebuilding generated article modules."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def extract_article_content() -> str:
    source = ROOT / "article" / "source.md"
    if not source.exists():
        raise RuntimeError(
            "article/source.md not found. Restore the markdown source before rebuilding."
        )
    return source.read_text(encoding="utf-8")


def split_body_and_references(body_html: str) -> tuple[str, str]:
    marker = "<h2>References</h2>"
    if marker in body_html:
        body_part, refs_part = body_html.split(marker, 1)
    else:
        body_part, refs_part = body_html, ""
    return body_part, refs_part


def write_generated_modules(body_part: str, refs_part: str) -> tuple[Path, Path]:
    body_output = ROOT / "article" / "body_html.py"
    body_output.write_text(
        "# Auto-generated by scripts/build_body_html.py\n"
        f'BODY_HTML = """{body_part}"""\n',
        encoding="utf-8",
    )

    refs_output = ROOT / "article" / "references_html.py"
    refs_output.write_text(
        "# Auto-generated by scripts/build_body_html.py\n"
        f'REFERENCES_HTML = """{refs_part.strip()}"""\n',
        encoding="utf-8",
    )
    return body_output, refs_output
